# Generated by Django 3.0.7 on 2020-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('project_desc', models.TextField()),
                ('project_budget', models.CharField(max_length=16)),
                ('client_name', models.CharField(max_length=64)),
                ('client_phone', models.CharField(max_length=16)),
                ('client_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
