# Generated by Django 3.0.6 on 2020-10-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'Qr5Pg65163lLPzRs5G5Njhzgbu8SMqmljKsgj0nvQI8='),
        ),
        migrations.AddField(
            model_name='message',
            name='send_status',
            field=models.PositiveSmallIntegerField(choices=[('NOT_SENT', 0), ('SENT', 1), ('DELIVERED', 2)], default=0),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-ToKgHHW1sSZRN7SW', max_length=16),
        ),
    ]
