# Generated by Django 3.0.6 on 2020-11-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0002_auto_20201018_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'B2yiiXs5zLOmac-7sj5MmmnPya4mwGUQNrKXRX6nrgM='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-WhSSidKcU6nCCG8L', max_length=16),
        ),
    ]
