# Generated by Django 3.0.6 on 2020-12-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0004_auto_20201223_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b's-oRw7WRJM3zqZtHpD5fTkaA4O6gTQ9oiafOSBQfvPo='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-2a3buZcEA5vHZEre', max_length=32),
        ),
    ]
