# Generated by Django 3.0.6 on 2020-12-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0006_auto_20201223_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'0Hd3YPr0gFZc0dkWolUct6BZFVaXo-MCk-GT7v3LHqo='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-dQC4h9vx-l2zi2Un', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='mode_of_payment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'OFFLINE'), (1, 'ONLINE')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'HEALTH'), (1, 'SEX'), (2, 'BODY_BUILDING'), (3, 'TECH')], default=None),
        ),
    ]
