# Generated by Django 3.0.6 on 2020-12-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0008_auto_20201224_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'mXfs2t-dFtlUCjUvhYyhKdDrzITDUjSSEIHoIqUfkmQ='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-fT68aMH0FVSfaI_F', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_payment',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
