# Generated by Django 3.0.6 on 2020-12-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0009_auto_20201224_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'EhQJcbuEv9AzxcDagHoKl6zNpbAOY7Ms184SUCLsRss='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-q-yG3lF0kGFtPkv_', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
