# Generated by Django 3.0.6 on 2020-12-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0010_auto_20201224_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='evidence',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Anonymous/evidence'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'aMFW1dgQ-w6T7z033i365CHxnzrJIXT_Ra1eqgWLQ7A='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-07el1KhKOEnBk6J2', max_length=32),
        ),
    ]
