# Generated by Django 3.0.6 on 2020-12-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0011_auto_20201226_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='evidence',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'2F-mmje7_z7uKtHQQXFjNezJS88wtbCZuB3fDQsYB58='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-DpdUupfsRbse8hMi', max_length=32),
        ),
    ]
