# Generated by Django 3.0.6 on 2020-12-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0012_auto_20201226_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_msg',
            field=models.TextField(default='{"consultant": [], "client": []}'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'pvy3ba4ZljnnZOxvurMyb9q-g3D7nSvmsopQqfqTr_4='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-4q5JqnUIwXq73tnr', max_length=32),
        ),
    ]
