# Generated by Django 3.0.6 on 2020-12-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0013_auto_20201228_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'TMp3FvCThGNnCJALBkyQZr1Y4QzdQ7jxtUHMo-08HrE='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-PKbMZddocvkMf7IT', max_length=32),
        ),
    ]
