# Generated by Django 3.0.6 on 2020-12-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0014_auto_20201228_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='evidence',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Evidence'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'xzUoxkPyd2-8yqhIfhqASNgzKdOnU83vDjIGnRY8TZ0='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-tQbv2RnX4hh8NPL4', max_length=32),
        ),
    ]
