# Generated by Django 3.0.6 on 2020-12-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0015_auto_20201228_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'iDto4Al0bdO5tobl8T4f1jlLio0VScGUKZmx6w7sw48='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-q-ep7SyrPsLvYWkR', max_length=32),
        ),
    ]
