# Generated by Django 3.0.6 on 2021-01-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0016_auto_20201229_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='bank_account',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='consultant',
            name='bank_account_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consultant',
            name='bank_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'u3j9JkgYjRdxqhgICpHNlHv5kbDtZo56swiCIBYqpaA='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-KpJcwmBRWQB6kHuh', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
