# Generated by Django 3.0.6 on 2021-01-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0019_auto_20210103_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'KLf-rio1kA-ZRbdS_30d2fJ0U8QUPy_yTrpbikHJD28='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-JNvqDCkWILCbZcAg', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
