# Generated by Django 3.0.6 on 2021-01-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0020_auto_20210103_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='consultant',
            name='whatsapp_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='beauty_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='children_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='defender_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='general_wellbeing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='parents_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sex_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'bdxX6MGo9ehqlKBwYqj4VtaNHhtmcLsLREoabe4xpKI='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-_9Jppnv4tGCK-haC', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(choices=[('40_plus_men.jpg', '40 PLUS MEN'), ('40_plus_woman.jpg', '40 PLUS WOMAN'), ('a_and_r.jpg', 'A AND R'), ('african_potato.jpg', 'AFRICAN POTATO'), ('aloe_vite.jpg', 'ALOE VITE'), ('butchu_detox.jpg', 'BUTCHU DETOX'), ('calmag_plus.jpg', 'CALMAG PLUS'), ('calmeeze.jpg', 'CALMEEZE'), ('defender.jpg', 'DEFENDER'), ('dia_garde.jpg', 'DIA GARDE'), ('eye_garde.jpg', 'EYE GARDE'), ('hair_skin.jpg', 'HAIR SKIN'), ('kardio_garde.jpg', 'KARDIO GARDE'), ('kid_garde.jpg', 'KID GARDE'), ('memory_garde.jpg', 'MEMORY GARDE'), ('multi_vite.jpg', 'MULTI VITE'), ('omega_plus.jpg', 'OMEGA PLUS'), ('pro_b.jpg', 'PRO B'), ('rock_garde.jpg', 'ROCK GARDE'), ('sea_vital.jpg', 'SEA VITAL'), ('slim_garde_cla.jpg', 'SLIM GARDE CLA'), ('slim_garde_protein.jpg', 'SLIM GARDE PROTEIN'), ('slimgarde_kickstart.jpg', 'SLIMGARDE KICKSTART'), ('stress_garde.jpg', 'STRESS GARDE'), ('super_cider_plus.jpg', 'SUPER CIDER PLUS')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
