# Generated by Django 3.0.6 on 2021-01-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anonymous', '0021_auto_20210103_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.BinaryField(default=b'jukDkr-RiVrJPZDPbTg_9vMXRrf1S6xZS-_YFHpN468='),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='code',
            field=models.CharField(default='Consult-AarQDI8dB5BbC7u2', max_length=32),
        ),
    ]
